{
  "openapi": "3.0.0",
  "paths": {
    "/": {
      "get": {
        "operationId": "AppController_getWelcome",
        "parameters": [],
        "responses": {
          "405": {
            "description": "Method not allowed"
          },
          "408": {
            "description": "Request timeout"
          },
          "429": {
            "description": "Too many requests"
          },
          "500": {
            "description": "Internal server error"
          },
          "501": {
            "description": "Not implemented"
          },
          "502": {
            "description": "Bad gateway"
          },
          "503": {
            "description": "Service unavailable"
          },
          "504": {
            "description": "Gateway timeout"
          },
          "505": {
            "description": "HTTP version not supported"
          },
          "507": {
            "description": "Insufficient storage"
          },
          "508": {
            "description": "Loop detected"
          },
          "default": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        },
        "tags": ["Welcome"]
      }
    },
    "/auth/login": {
      "post": {
        "operationId": "AuthController_login",
        "parameters": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/LoginDto"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successfully logged in",
            "headers": {
              "Set-Cookie": {
                "description": "HttpOnly cookies: access_token Ð¸ refresh_token",
                "schema": {
                  "type": "string",
                  "example": "access_token=<jwt>; HttpOnly; Path=/; SameSite=Lax;\nrefresh_token=<jwt>; HttpOnly; Path=/; SameSite=Lax;"
                }
              }
            }
          },
          "400": {
            "description": "Validation error",
            "content": {
              "application/json": {
                "example": {
                  "errors": [
                    {
                      "field": "email",
                      "message": "email must be an email"
                    }
                  ]
                }
              }
            }
          },
          "401": {
            "description": "Invalid credentials"
          },
          "405": {
            "description": "Method not allowed"
          },
          "408": {
            "description": "Request timeout"
          },
          "429": {
            "description": "Too many requests"
          },
          "500": {
            "description": "Internal server error"
          },
          "501": {
            "description": "Not implemented"
          },
          "502": {
            "description": "Bad gateway"
          },
          "503": {
            "description": "Service unavailable"
          },
          "504": {
            "description": "Gateway timeout"
          },
          "505": {
            "description": "HTTP version not supported"
          },
          "507": {
            "description": "Insufficient storage"
          },
          "508": {
            "description": "Loop detected"
          },
          "default": {
            "description": ""
          }
        },
        "summary": "User login",
        "tags": ["Auth"]
      }
    },
    "/auth/registration": {
      "post": {
        "operationId": "AuthController_registration",
        "parameters": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RegistrationDto"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successfully registered"
          },
          "400": {
            "description": "Validation error",
            "content": {
              "application/json": {
                "example": {
                  "errors": [
                    {
                      "field": "email",
                      "message": "email must be an email"
                    }
                  ]
                }
              }
            }
          },
          "405": {
            "description": "Method not allowed"
          },
          "408": {
            "description": "Request timeout"
          },
          "409": {
            "description": "User already exists"
          },
          "429": {
            "description": "Too many requests"
          },
          "500": {
            "description": "Internal server error"
          },
          "501": {
            "description": "Not implemented"
          },
          "502": {
            "description": "Bad gateway"
          },
          "503": {
            "description": "Service unavailable"
          },
          "504": {
            "description": "Gateway timeout"
          },
          "505": {
            "description": "HTTP version not supported"
          },
          "507": {
            "description": "Insufficient storage"
          },
          "508": {
            "description": "Loop detected"
          },
          "default": {
            "description": ""
          }
        },
        "summary": "User registration",
        "tags": ["Auth"]
      }
    },
    "/auth/logout": {
      "post": {
        "operationId": "AuthController_logout",
        "parameters": [],
        "responses": {
          "201": {
            "description": "Successfully logged out"
          },
          "401": {
            "description": "Unauthorized"
          },
          "405": {
            "description": "Method not allowed"
          },
          "408": {
            "description": "Request timeout"
          },
          "429": {
            "description": "Too many requests"
          },
          "500": {
            "description": "Internal server error"
          },
          "501": {
            "description": "Not implemented"
          },
          "502": {
            "description": "Bad gateway"
          },
          "503": {
            "description": "Service unavailable"
          },
          "504": {
            "description": "Gateway timeout"
          },
          "505": {
            "description": "HTTP version not supported"
          },
          "507": {
            "description": "Insufficient storage"
          },
          "508": {
            "description": "Loop detected"
          },
          "default": {
            "description": ""
          }
        },
        "security": [
          {
            "access_token": []
          }
        ],
        "summary": "User logout",
        "tags": ["Auth"]
      }
    },
    "/auth/refresh": {
      "post": {
        "operationId": "AuthController_refresh",
        "parameters": [],
        "responses": {
          "201": {
            "description": "Token refreshed",
            "headers": {
              "Set-Cookie": {
                "description": "HttpOnly cookies: access_token",
                "schema": {
                  "type": "string",
                  "example": "access_token=<jwt>; HttpOnly; Path=/; SameSite=Lax;"
                }
              }
            }
          },
          "400": {
            "description": "Refresh token not provided"
          },
          "401": {
            "description": "Invalid or expired refresh token"
          },
          "405": {
            "description": "Method not allowed"
          },
          "408": {
            "description": "Request timeout"
          },
          "429": {
            "description": "Too many requests"
          },
          "500": {
            "description": "Internal server error"
          },
          "501": {
            "description": "Not implemented"
          },
          "502": {
            "description": "Bad gateway"
          },
          "503": {
            "description": "Service unavailable"
          },
          "504": {
            "description": "Gateway timeout"
          },
          "505": {
            "description": "HTTP version not supported"
          },
          "507": {
            "description": "Insufficient storage"
          },
          "508": {
            "description": "Loop detected"
          },
          "default": {
            "description": ""
          }
        },
        "security": [
          {
            "refresh_token": []
          }
        ],
        "summary": "Refresh access token",
        "tags": ["Auth"]
      }
    },
    "/auth/me": {
      "get": {
        "operationId": "AuthController_getMe",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successfully logged out",
            "content": {
              "application/json": {
                "example": {
                  "createdAt": "2023-10-01T12:00:00.000Z",
                  "email": "user@example.com",
                  "id": "1234567890abcdef",
                  "updatedAt": "2023-10-01T12:00:00.000Z",
                  "username": "user123",
                  "avatar": null,
                  "description": "Some description about the user"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "405": {
            "description": "Method not allowed"
          },
          "408": {
            "description": "Request timeout"
          },
          "429": {
            "description": "Too many requests"
          },
          "500": {
            "description": "Internal server error"
          },
          "501": {
            "description": "Not implemented"
          },
          "502": {
            "description": "Bad gateway"
          },
          "503": {
            "description": "Service unavailable"
          },
          "504": {
            "description": "Gateway timeout"
          },
          "505": {
            "description": "HTTP version not supported"
          },
          "507": {
            "description": "Insufficient storage"
          },
          "508": {
            "description": "Loop detected"
          },
          "default": {
            "description": ""
          }
        },
        "security": [
          {
            "access_token": []
          }
        ],
        "summary": "Get current authenticated user",
        "tags": ["Auth"]
      }
    },
    "/users": {
      "get": {
        "operationId": "UsersController_getAll",
        "parameters": [
          {
            "name": "limit",
            "required": false,
            "in": "path",
            "description": "Number of users to return per page",
            "schema": {
              "type": "number"
            }
          },
          {
            "name": "page",
            "required": false,
            "in": "path",
            "description": "Page number for pagination",
            "schema": {
              "type": "number"
            }
          },
          {
            "name": "username",
            "required": false,
            "in": "path",
            "description": "Filter users by username",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "List of users retrieved successfully",
            "content": {
              "application/json": {
                "example": [
                  {
                    "id": "1",
                    "username": "user1",
                    "avatar": "https://example.com/uploads/avatars/avatar.jpg",
                    "backgroundImage": "",
                    "bio": "Some bio",
                    "createdAt": "2025-08-02T11:43:17.703Z"
                  },
                  {
                    "id": "2",
                    "username": "user2",
                    "avatar": "https://example.com/uploads/avatars/avatar.jpg",
                    "backgroundImage": "",
                    "bio": "Some bio 2",
                    "createdAt": "2025-08-02T11:43:17.703Z"
                  }
                ]
              }
            }
          },
          "405": {
            "description": "Method not allowed"
          },
          "408": {
            "description": "Request timeout"
          },
          "429": {
            "description": "Too many requests"
          },
          "500": {
            "description": "Internal server error"
          },
          "501": {
            "description": "Not implemented"
          },
          "502": {
            "description": "Bad gateway"
          },
          "503": {
            "description": "Service unavailable"
          },
          "504": {
            "description": "Gateway timeout"
          },
          "505": {
            "description": "HTTP version not supported"
          },
          "507": {
            "description": "Insufficient storage"
          },
          "508": {
            "description": "Loop detected"
          },
          "default": {
            "description": ""
          }
        },
        "summary": "Get all users with filters and pagination",
        "tags": ["Users"]
      },
      "put": {
        "operationId": "UsersController_putById",
        "parameters": [],
        "requestBody": {
          "required": true,
          "description": "User data to update",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateUserDto"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "User profile updated successfully",
            "content": {
              "application/json": {
                "example": {
                  "id": "1",
                  "username": "user1",
                  "avatar": "https://example.com/uploads/avatars/avatar.jpg",
                  "backgroundImage": "",
                  "bio": "Some bio",
                  "createdAt": "2025-08-02T11:43:17.704Z"
                }
              }
            }
          },
          "405": {
            "description": "Method not allowed"
          },
          "408": {
            "description": "Request timeout"
          },
          "429": {
            "description": "Too many requests"
          },
          "500": {
            "description": "Internal server error"
          },
          "501": {
            "description": "Not implemented"
          },
          "502": {
            "description": "Bad gateway"
          },
          "503": {
            "description": "Service unavailable"
          },
          "504": {
            "description": "Gateway timeout"
          },
          "505": {
            "description": "HTTP version not supported"
          },
          "507": {
            "description": "Insufficient storage"
          },
          "508": {
            "description": "Loop detected"
          },
          "default": {
            "description": ""
          }
        },
        "security": [
          {
            "access_token": []
          }
        ],
        "summary": "Update user by id",
        "tags": ["Users"]
      }
    },
    "/users/username/{username}": {
      "get": {
        "operationId": "UsersController_getByUsername",
        "parameters": [
          {
            "name": "username",
            "required": true,
            "in": "path",
            "description": "Username of the user to retrieve",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "User retrieved successfully",
            "content": {
              "application/json": {
                "example": {
                  "id": "1",
                  "username": "user1",
                  "avatar": "https://example.com/uploads/avatars/avatar.jpg",
                  "backgroundImage": "",
                  "bio": "Some bio",
                  "createdAt": "2025-08-02T11:43:17.704Z"
                }
              }
            }
          },
          "404": {
            "description": "User not found"
          },
          "405": {
            "description": "Method not allowed"
          },
          "408": {
            "description": "Request timeout"
          },
          "429": {
            "description": "Too many requests"
          },
          "500": {
            "description": "Internal server error"
          },
          "501": {
            "description": "Not implemented"
          },
          "502": {
            "description": "Bad gateway"
          },
          "503": {
            "description": "Service unavailable"
          },
          "504": {
            "description": "Gateway timeout"
          },
          "505": {
            "description": "HTTP version not supported"
          },
          "507": {
            "description": "Insufficient storage"
          },
          "508": {
            "description": "Loop detected"
          },
          "default": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                }
              }
            }
          }
        },
        "summary": "Get user by username",
        "tags": ["Users"]
      }
    },
    "/users/{id}": {
      "get": {
        "operationId": "UsersController_getById",
        "parameters": [],
        "responses": {
          "200": {
            "description": "User retrieved successfully",
            "content": {
              "application/json": {
                "example": {
                  "id": "1",
                  "username": "user1",
                  "avatar": "https://example.com/uploads/avatars/avatar.jpg",
                  "backgroundImage": "",
                  "bio": "Some bio",
                  "createdAt": "2025-08-02T11:43:17.704Z"
                }
              }
            }
          },
          "405": {
            "description": "Method not allowed"
          },
          "408": {
            "description": "Request timeout"
          },
          "429": {
            "description": "Too many requests"
          },
          "500": {
            "description": "Internal server error"
          },
          "501": {
            "description": "Not implemented"
          },
          "502": {
            "description": "Bad gateway"
          },
          "503": {
            "description": "Service unavailable"
          },
          "504": {
            "description": "Gateway timeout"
          },
          "505": {
            "description": "HTTP version not supported"
          },
          "507": {
            "description": "Insufficient storage"
          },
          "508": {
            "description": "Loop detected"
          },
          "default": {
            "description": ""
          }
        },
        "summary": "Get user by id",
        "tags": ["Users"]
      }
    },
    "/users/avatar": {
      "post": {
        "operationId": "UsersController_uploadAvatar",
        "parameters": [],
        "requestBody": {
          "required": true,
          "description": "Avatar file to upload",
          "content": {
            "multipart/form-data": {
              "schema": {
                "$ref": "#/components/schemas/UploadAvatarDto"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Avatar uploaded successfully",
            "content": {
              "application/json": {
                "example": {
                  "id": "1",
                  "username": "user1",
                  "avatar": "https://example.com/uploads/avatars/avatar.jpg",
                  "backgroundImage": "",
                  "bio": "Some bio",
                  "createdAt": "2025-08-02T11:43:17.713Z",
                  "email": "example@gmail.com"
                }
              }
            }
          },
          "405": {
            "description": "Method not allowed"
          },
          "408": {
            "description": "Request timeout"
          },
          "422": {
            "description": "Invalid file type or size"
          },
          "429": {
            "description": "Too many requests"
          },
          "500": {
            "description": "Internal server error"
          },
          "501": {
            "description": "Not implemented"
          },
          "502": {
            "description": "Bad gateway"
          },
          "503": {
            "description": "Service unavailable"
          },
          "504": {
            "description": "Gateway timeout"
          },
          "505": {
            "description": "HTTP version not supported"
          },
          "507": {
            "description": "Insufficient storage"
          },
          "508": {
            "description": "Loop detected"
          },
          "default": {
            "description": ""
          }
        },
        "security": [
          {
            "access_token": []
          }
        ],
        "summary": "Upload avatar for user",
        "tags": ["Users"]
      }
    },
    "/artists": {
      "get": {
        "operationId": "ArtistsController_getAll",
        "parameters": [
          {
            "name": "page",
            "required": false,
            "in": "query",
            "description": "Page number",
            "schema": {
              "example": 1,
              "type": "number"
            }
          },
          {
            "name": "limit",
            "required": false,
            "in": "query",
            "description": "Items per page",
            "schema": {
              "example": 10,
              "type": "number"
            }
          },
          {
            "name": "username",
            "required": false,
            "in": "query",
            "description": "Search by artist username",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "example": [
                  {
                    "avatar": "https://example.com/avatar.jpg",
                    "id": "1",
                    "username": "artist1",
                    "backgroundImage": "",
                    "bio": ""
                  }
                ]
              }
            },
            "description": ""
          },
          "405": {
            "description": "Method not allowed"
          },
          "408": {
            "description": "Request timeout"
          },
          "429": {
            "description": "Too many requests"
          },
          "500": {
            "description": "Internal server error"
          },
          "501": {
            "description": "Not implemented"
          },
          "502": {
            "description": "Bad gateway"
          },
          "503": {
            "description": "Service unavailable"
          },
          "504": {
            "description": "Gateway timeout"
          },
          "505": {
            "description": "HTTP version not supported"
          },
          "507": {
            "description": "Insufficient storage"
          },
          "508": {
            "description": "Loop detected"
          },
          "default": {
            "description": ""
          }
        },
        "summary": "Get all artists with pagination",
        "tags": ["Artists"]
      },
      "post": {
        "operationId": "ArtistsController_create",
        "parameters": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateArtistDto"
              }
            }
          }
        },
        "responses": {
          "405": {
            "description": "Method not allowed"
          },
          "408": {
            "description": "Request timeout"
          },
          "429": {
            "description": "Too many requests"
          },
          "500": {
            "description": "Internal server error"
          },
          "501": {
            "description": "Not implemented"
          },
          "502": {
            "description": "Bad gateway"
          },
          "503": {
            "description": "Service unavailable"
          },
          "504": {
            "description": "Gateway timeout"
          },
          "505": {
            "description": "HTTP version not supported"
          },
          "507": {
            "description": "Insufficient storage"
          },
          "508": {
            "description": "Loop detected"
          },
          "default": {
            "description": ""
          }
        },
        "summary": "Create a new artist",
        "tags": ["Artists"]
      }
    },
    "/artists/{id}": {
      "get": {
        "operationId": "ArtistsController_getById",
        "parameters": [],
        "responses": {
          "405": {
            "description": "Method not allowed"
          },
          "408": {
            "description": "Request timeout"
          },
          "429": {
            "description": "Too many requests"
          },
          "500": {
            "description": "Internal server error"
          },
          "501": {
            "description": "Not implemented"
          },
          "502": {
            "description": "Bad gateway"
          },
          "503": {
            "description": "Service unavailable"
          },
          "504": {
            "description": "Gateway timeout"
          },
          "505": {
            "description": "HTTP version not supported"
          },
          "507": {
            "description": "Insufficient storage"
          },
          "508": {
            "description": "Loop detected"
          },
          "default": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                }
              }
            }
          }
        },
        "summary": "Get artist by id",
        "tags": ["Artists"]
      },
      "put": {
        "operationId": "ArtistsController_updateProfile",
        "parameters": [],
        "responses": {
          "405": {
            "description": "Method not allowed"
          },
          "408": {
            "description": "Request timeout"
          },
          "429": {
            "description": "Too many requests"
          },
          "500": {
            "description": "Internal server error"
          },
          "501": {
            "description": "Not implemented"
          },
          "502": {
            "description": "Bad gateway"
          },
          "503": {
            "description": "Service unavailable"
          },
          "504": {
            "description": "Gateway timeout"
          },
          "505": {
            "description": "HTTP version not supported"
          },
          "507": {
            "description": "Insufficient storage"
          },
          "508": {
            "description": "Loop detected"
          },
          "default": {
            "description": ""
          }
        },
        "security": [
          {
            "access_token": []
          }
        ],
        "summary": "Update artist profile",
        "tags": ["Artists"]
      },
      "delete": {
        "operationId": "ArtistsController_deleteProfile",
        "parameters": [],
        "responses": {
          "405": {
            "description": "Method not allowed"
          },
          "408": {
            "description": "Request timeout"
          },
          "429": {
            "description": "Too many requests"
          },
          "500": {
            "description": "Internal server error"
          },
          "501": {
            "description": "Not implemented"
          },
          "502": {
            "description": "Bad gateway"
          },
          "503": {
            "description": "Service unavailable"
          },
          "504": {
            "description": "Gateway timeout"
          },
          "505": {
            "description": "HTTP version not supported"
          },
          "507": {
            "description": "Insufficient storage"
          },
          "508": {
            "description": "Loop detected"
          },
          "default": {
            "description": ""
          }
        },
        "security": [
          {
            "access_token": []
          }
        ],
        "summary": "Delete artist profile",
        "tags": ["Artists"]
      }
    },
    "/artists/username/{username}": {
      "get": {
        "operationId": "ArtistsController_getByUsername",
        "parameters": [],
        "responses": {
          "405": {
            "description": "Method not allowed"
          },
          "408": {
            "description": "Request timeout"
          },
          "429": {
            "description": "Too many requests"
          },
          "500": {
            "description": "Internal server error"
          },
          "501": {
            "description": "Not implemented"
          },
          "502": {
            "description": "Bad gateway"
          },
          "503": {
            "description": "Service unavailable"
          },
          "504": {
            "description": "Gateway timeout"
          },
          "505": {
            "description": "HTTP version not supported"
          },
          "507": {
            "description": "Insufficient storage"
          },
          "508": {
            "description": "Loop detected"
          },
          "default": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                }
              }
            }
          }
        },
        "summary": "Get artist by username",
        "tags": ["Artists"]
      }
    },
    "/tracks": {
      "get": {
        "operationId": "TracksController_getAll",
        "parameters": [
          {
            "name": "page",
            "required": false,
            "in": "query",
            "description": "Page number",
            "schema": {
              "example": 1,
              "type": "number"
            }
          },
          {
            "name": "limit",
            "required": false,
            "in": "query",
            "description": "Items per page",
            "schema": {
              "example": 10,
              "type": "number"
            }
          },
          {
            "name": "title",
            "required": false,
            "in": "query",
            "description": "Search by track title",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "example": [
                  {
                    "artist": "123",
                    "title": "Track Title",
                    "id": "1",
                    "likedBy": [],
                    "album": "Album Name",
                    "albumId": "album123",
                    "artistId": "artist123",
                    "cover": "https://example.com/cover.jpg",
                    "audioUrl": "",
                    "userId": "",
                    "createdAt": "2025-08-02T11:43:17.731Z"
                  }
                ]
              }
            },
            "description": ""
          },
          "405": {
            "description": "Method not allowed"
          },
          "408": {
            "description": "Request timeout"
          },
          "429": {
            "description": "Too many requests"
          },
          "500": {
            "description": "Internal server error"
          },
          "501": {
            "description": "Not implemented"
          },
          "502": {
            "description": "Bad gateway"
          },
          "503": {
            "description": "Service unavailable"
          },
          "504": {
            "description": "Gateway timeout"
          },
          "505": {
            "description": "HTTP version not supported"
          },
          "507": {
            "description": "Insufficient storage"
          },
          "508": {
            "description": "Loop detected"
          },
          "default": {
            "description": ""
          }
        },
        "summary": "Get all tracks with pagination",
        "tags": ["Tracks"]
      },
      "post": {
        "operationId": "TracksController_postTrack",
        "parameters": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateTrackDto"
              }
            }
          }
        },
        "responses": {
          "201": {
            "content": {
              "application/json": {
                "example": {
                  "id": "1",
                  "title": "Track Title",
                  "cover": "https://example.com/cover.jpg",
                  "audioUrl": "",
                  "createdAt": "2025-08-02T11:43:17.731Z"
                }
              }
            },
            "description": ""
          },
          "405": {
            "description": "Method not allowed"
          },
          "408": {
            "description": "Request timeout"
          },
          "429": {
            "description": "Too many requests"
          },
          "500": {
            "description": "Internal server error"
          },
          "501": {
            "description": "Not implemented"
          },
          "502": {
            "description": "Bad gateway"
          },
          "503": {
            "description": "Service unavailable"
          },
          "504": {
            "description": "Gateway timeout"
          },
          "505": {
            "description": "HTTP version not supported"
          },
          "507": {
            "description": "Insufficient storage"
          },
          "508": {
            "description": "Loop detected"
          },
          "default": {
            "description": ""
          }
        },
        "security": [
          {
            "access_token": []
          },
          {
            "access_token": []
          }
        ],
        "summary": "Create track",
        "tags": ["Tracks"]
      }
    },
    "/tracks/{id}": {
      "get": {
        "operationId": "TracksController_getById",
        "parameters": [],
        "responses": {
          "405": {
            "description": "Method not allowed"
          },
          "408": {
            "description": "Request timeout"
          },
          "429": {
            "description": "Too many requests"
          },
          "500": {
            "description": "Internal server error"
          },
          "501": {
            "description": "Not implemented"
          },
          "502": {
            "description": "Bad gateway"
          },
          "503": {
            "description": "Service unavailable"
          },
          "504": {
            "description": "Gateway timeout"
          },
          "505": {
            "description": "HTTP version not supported"
          },
          "507": {
            "description": "Insufficient storage"
          },
          "508": {
            "description": "Loop detected"
          },
          "default": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                }
              }
            }
          }
        },
        "summary": "Get track by id",
        "tags": ["Tracks"]
      },
      "put": {
        "operationId": "TracksController_putTrack",
        "parameters": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateTrackDto"
              }
            }
          }
        },
        "responses": {
          "405": {
            "description": "Method not allowed"
          },
          "408": {
            "description": "Request timeout"
          },
          "429": {
            "description": "Too many requests"
          },
          "500": {
            "description": "Internal server error"
          },
          "501": {
            "description": "Not implemented"
          },
          "502": {
            "description": "Bad gateway"
          },
          "503": {
            "description": "Service unavailable"
          },
          "504": {
            "description": "Gateway timeout"
          },
          "505": {
            "description": "HTTP version not supported"
          },
          "507": {
            "description": "Insufficient storage"
          },
          "508": {
            "description": "Loop detected"
          },
          "default": {
            "description": ""
          }
        },
        "security": [
          {
            "access_token": []
          }
        ],
        "summary": "Update track by id",
        "tags": ["Tracks"]
      }
    },
    "/playlists": {
      "get": {
        "operationId": "PlaylistsController_getAll",
        "parameters": [
          {
            "name": "page",
            "required": false,
            "in": "path",
            "description": "Page number for pagination",
            "schema": {
              "type": "number"
            }
          },
          {
            "name": "limit",
            "required": false,
            "in": "path",
            "description": "Number of items per page",
            "schema": {
              "type": "number"
            }
          }
        ],
        "responses": {
          "405": {
            "description": "Method not allowed"
          },
          "408": {
            "description": "Request timeout"
          },
          "429": {
            "description": "Too many requests"
          },
          "500": {
            "description": "Internal server error"
          },
          "501": {
            "description": "Not implemented"
          },
          "502": {
            "description": "Bad gateway"
          },
          "503": {
            "description": "Service unavailable"
          },
          "504": {
            "description": "Gateway timeout"
          },
          "505": {
            "description": "HTTP version not supported"
          },
          "507": {
            "description": "Insufficient storage"
          },
          "508": {
            "description": "Loop detected"
          },
          "default": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object"
                  }
                }
              }
            }
          }
        },
        "summary": "Get all playlists with pagination and filters",
        "tags": ["Playlists"]
      },
      "post": {
        "operationId": "PlaylistsController_post",
        "parameters": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreatePlaylistDto"
              }
            }
          }
        },
        "responses": {
          "405": {
            "description": "Method not allowed"
          },
          "408": {
            "description": "Request timeout"
          },
          "429": {
            "description": "Too many requests"
          },
          "500": {
            "description": "Internal server error"
          },
          "501": {
            "description": "Not implemented"
          },
          "502": {
            "description": "Bad gateway"
          },
          "503": {
            "description": "Service unavailable"
          },
          "504": {
            "description": "Gateway timeout"
          },
          "505": {
            "description": "HTTP version not supported"
          },
          "507": {
            "description": "Insufficient storage"
          },
          "508": {
            "description": "Loop detected"
          },
          "default": {
            "description": ""
          }
        },
        "security": [
          {
            "access_token": []
          }
        ],
        "summary": "Create a new playlist",
        "tags": ["Playlists"]
      }
    },
    "/playlists/{id}": {
      "get": {
        "operationId": "PlaylistsController_getById",
        "parameters": [],
        "responses": {
          "405": {
            "description": "Method not allowed"
          },
          "408": {
            "description": "Request timeout"
          },
          "429": {
            "description": "Too many requests"
          },
          "500": {
            "description": "Internal server error"
          },
          "501": {
            "description": "Not implemented"
          },
          "502": {
            "description": "Bad gateway"
          },
          "503": {
            "description": "Service unavailable"
          },
          "504": {
            "description": "Gateway timeout"
          },
          "505": {
            "description": "HTTP version not supported"
          },
          "507": {
            "description": "Insufficient storage"
          },
          "508": {
            "description": "Loop detected"
          },
          "default": {
            "description": ""
          }
        },
        "summary": "Get playlist by id",
        "tags": ["Playlists"]
      },
      "put": {
        "operationId": "PlaylistsController_update",
        "parameters": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdatePlaylistDto"
              }
            }
          }
        },
        "responses": {
          "405": {
            "description": "Method not allowed"
          },
          "408": {
            "description": "Request timeout"
          },
          "429": {
            "description": "Too many requests"
          },
          "500": {
            "description": "Internal server error"
          },
          "501": {
            "description": "Not implemented"
          },
          "502": {
            "description": "Bad gateway"
          },
          "503": {
            "description": "Service unavailable"
          },
          "504": {
            "description": "Gateway timeout"
          },
          "505": {
            "description": "HTTP version not supported"
          },
          "507": {
            "description": "Insufficient storage"
          },
          "508": {
            "description": "Loop detected"
          },
          "default": {
            "description": ""
          }
        },
        "security": [
          {
            "access_token": []
          }
        ],
        "summary": "Update playlist by id",
        "tags": ["Playlists"]
      }
    },
    "/albums": {
      "get": {
        "operationId": "AlbumsController_getAllAlbums",
        "parameters": [
          {
            "name": "page",
            "required": true,
            "in": "query",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "limit",
            "required": true,
            "in": "query",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "405": {
            "description": "Method not allowed"
          },
          "408": {
            "description": "Request timeout"
          },
          "429": {
            "description": "Too many requests"
          },
          "500": {
            "description": "Internal server error"
          },
          "501": {
            "description": "Not implemented"
          },
          "502": {
            "description": "Bad gateway"
          },
          "503": {
            "description": "Service unavailable"
          },
          "504": {
            "description": "Gateway timeout"
          },
          "505": {
            "description": "HTTP version not supported"
          },
          "507": {
            "description": "Insufficient storage"
          },
          "508": {
            "description": "Loop detected"
          },
          "default": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object"
                  }
                }
              }
            }
          }
        },
        "summary": "Get all albums with pagination and filters",
        "tags": ["Albums"]
      },
      "post": {
        "operationId": "AlbumsController_createAlbum",
        "parameters": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateAlbumDto"
              }
            }
          }
        },
        "responses": {
          "405": {
            "description": "Method not allowed"
          },
          "408": {
            "description": "Request timeout"
          },
          "429": {
            "description": "Too many requests"
          },
          "500": {
            "description": "Internal server error"
          },
          "501": {
            "description": "Not implemented"
          },
          "502": {
            "description": "Bad gateway"
          },
          "503": {
            "description": "Service unavailable"
          },
          "504": {
            "description": "Gateway timeout"
          },
          "505": {
            "description": "HTTP version not supported"
          },
          "507": {
            "description": "Insufficient storage"
          },
          "508": {
            "description": "Loop detected"
          },
          "default": {
            "description": ""
          }
        },
        "security": [
          {
            "access_token": []
          }
        ],
        "summary": "Create a new album",
        "tags": ["Albums"]
      }
    },
    "/albums/{id}": {
      "get": {
        "operationId": "AlbumsController_getById",
        "parameters": [],
        "responses": {
          "405": {
            "description": "Method not allowed"
          },
          "408": {
            "description": "Request timeout"
          },
          "429": {
            "description": "Too many requests"
          },
          "500": {
            "description": "Internal server error"
          },
          "501": {
            "description": "Not implemented"
          },
          "502": {
            "description": "Bad gateway"
          },
          "503": {
            "description": "Service unavailable"
          },
          "504": {
            "description": "Gateway timeout"
          },
          "505": {
            "description": "HTTP version not supported"
          },
          "507": {
            "description": "Insufficient storage"
          },
          "508": {
            "description": "Loop detected"
          },
          "default": {
            "description": ""
          }
        },
        "summary": "Get album by id",
        "tags": ["Albums"]
      },
      "put": {
        "operationId": "AlbumsController_updateAlbum",
        "parameters": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateAlbumDto"
              }
            }
          }
        },
        "responses": {
          "405": {
            "description": "Method not allowed"
          },
          "408": {
            "description": "Request timeout"
          },
          "429": {
            "description": "Too many requests"
          },
          "500": {
            "description": "Internal server error"
          },
          "501": {
            "description": "Not implemented"
          },
          "502": {
            "description": "Bad gateway"
          },
          "503": {
            "description": "Service unavailable"
          },
          "504": {
            "description": "Gateway timeout"
          },
          "505": {
            "description": "HTTP version not supported"
          },
          "507": {
            "description": "Insufficient storage"
          },
          "508": {
            "description": "Loop detected"
          },
          "default": {
            "description": ""
          }
        },
        "security": [
          {
            "access_token": []
          }
        ],
        "summary": "Create a new album",
        "tags": ["Albums"]
      }
    }
  },
  "info": {
    "title": "@spotify/api",
    "description": "@spotify/api Swagger documentation",
    "version": "0.0.1",
    "contact": {
      "name": "Lordpluha",
      "url": "https://github.com/Lordpluha",
      "email": "vladislavteslyukofficial@gmail.com"
    }
  },
  "tags": [],
  "servers": [
    {
      "url": "http://localhost:3000",
      "description": "Local server"
    },
    {
      "url": "https://spotify-clone-api-jp5z.onrender.com/",
      "description": "Remote dev server"
    }
  ],
  "components": {
    "securitySchemes": {
      "oauth2": {
        "type": "openIdConnect",
        "flows": {}
      }
    },
    "schemas": {
      "SessionEntity": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "userId": {
            "type": "string"
          },
          "access_token": {
            "type": "string"
          },
          "refresh_token": {
            "type": "string"
          },
          "createdAt": {
            "format": "date-time",
            "type": "string"
          }
        },
        "required": [
          "id",
          "userId",
          "access_token",
          "refresh_token",
          "createdAt"
        ]
      },
      "LoginDto": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string",
            "description": "User email",
            "example": "user@example.com"
          },
          "password": {
            "type": "string",
            "description": "User password",
            "example": "password123"
          }
        },
        "required": ["email", "password"]
      },
      "RegistrationDto": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string",
            "description": "New user email",
            "example": "newuser@example.com"
          },
          "password": {
            "type": "string",
            "description": "New user password",
            "example": "password123"
          }
        },
        "required": ["email", "password"]
      },
      "UserEntity": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "username": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "createdAt": {
            "format": "date-time",
            "type": "string"
          },
          "description": {
            "type": "string",
            "nullable": true
          },
          "avatar": {
            "type": "string",
            "nullable": true
          }
        },
        "required": [
          "id",
          "username",
          "email",
          "password",
          "createdAt",
          "description",
          "avatar"
        ]
      },
      "UpdateUserDto": {
        "type": "object",
        "properties": {
          "username": {
            "type": "string",
            "description": "Username of the user",
            "example": "john_doe"
          },
          "email": {
            "type": "string",
            "description": "Email of the user",
            "example": "example@gmail.com"
          },
          "description": {
            "type": "string",
            "description": "Description of the user",
            "example": "This is a sample description"
          }
        },
        "required": ["username", "email"]
      },
      "UploadAvatarDto": {
        "type": "object",
        "properties": {
          "avatar": {
            "type": "string",
            "description": "User avatar",
            "format": "binary"
          }
        },
        "required": ["avatar"]
      },
      "CreateArtistDto": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string",
            "description": "User email",
            "example": "user@example.com"
          },
          "password": {
            "type": "string",
            "description": "User password",
            "example": "password123"
          },
          "username": {
            "type": "string",
            "description": "User username",
            "example": "user123"
          }
        },
        "required": ["email", "password", "username"]
      },
      "TrackEntity": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "title": {
            "type": "string"
          },
          "audioUrl": {
            "type": "string"
          },
          "cover": {
            "type": "string"
          },
          "createdAt": {
            "format": "date-time",
            "type": "string"
          },
          "artistId": {
            "type": "string"
          }
        },
        "required": [
          "id",
          "title",
          "audioUrl",
          "cover",
          "createdAt",
          "artistId"
        ]
      },
      "CreateTrackDto": {
        "type": "object",
        "properties": {
          "title": {
            "type": "string",
            "description": "Track title"
          },
          "audioUrl": {
            "type": "string",
            "description": "Url to audio"
          },
          "cover": {
            "type": "string",
            "description": "Url to cover image"
          }
        },
        "required": ["title", "audioUrl"]
      },
      "PlaylistEntity": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "title": {
            "type": "string"
          },
          "cover": {
            "type": "string"
          },
          "artistId": {
            "type": "string"
          },
          "description": {
            "type": "string",
            "nullable": true
          },
          "createdAt": {
            "format": "date-time",
            "type": "string"
          },
          "userId": {
            "type": "string"
          }
        },
        "required": [
          "id",
          "title",
          "cover",
          "artistId",
          "description",
          "createdAt",
          "userId"
        ]
      },
      "CreatePlaylistDto": {
        "type": "object",
        "properties": {
          "title": {
            "type": "string",
            "description": "Playlist title"
          },
          "description": {
            "type": "string",
            "description": "",
            "example": "user123"
          }
        },
        "required": ["title"]
      },
      "UpdatePlaylistDto": {
        "type": "object",
        "properties": {
          "title": {
            "type": "string",
            "description": "Playlist title"
          },
          "description": {
            "type": "string",
            "description": "",
            "example": "user123"
          }
        },
        "required": ["title"]
      },
      "UpdateAlbumDto": {
        "type": "object",
        "properties": {
          "title": {
            "type": "string",
            "description": "Playlist title"
          },
          "description": {
            "type": "string",
            "description": "",
            "example": "user123"
          }
        },
        "required": ["title"]
      },
      "CreateAlbumDto": {
        "type": "object",
        "properties": {
          "title": {
            "type": "string",
            "description": "Playlist title"
          },
          "description": {
            "type": "string",
            "description": "",
            "example": "user123"
          }
        },
        "required": ["title"]
      }
    }
  },
  "externalDocs": {
    "description": "Mintlify",
    "url": "https://lordpluha.mintlify.app/"
  }
}
